language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.3"
  - "3.4"
install:
  - pip install -e .[test]
  - pip install coverage coveralls
script:
  - coverage run setup.py test
after_success:
  - coveralls
